# Practical 1

In [2]:
def list_of_dict(heights):
    keys=heights.keys()
    values = zip(*[heights[k] for k in keys]) 
    result = [dict(zip(keys,v )) for v in values]
    return result

heights = {'Boys':[72,68,70,69,74], 'Girls':[63,65,69,62,61]}
print("\n ORIGINAL DICTIONARY OF LISTS :" , heights)
print("\n NOW LIST OF DICTIONARIES : \n",list_of_dict(heights))


('\n ORIGINAL DICTIONARY OF LISTS :', {'Boys': [72, 68, 70, 69, 74], 'Girls': [63, 65, 69, 62, 61]})
check some value
('\n NOW LIST OF DICTIONARIES : \n', [{'Boys': 72, 'Girls': 63}, {'Boys': 68, 'Girls': 65}, {'Boys': 70, 'Girls': 69}, {'Boys': 69, 'Girls': 62}, {'Boys': 74, 'Girls': 61}])


# Prcatical 2

In [2]:
import numpy as np

In [3]:
#part a
arr = np.random.randint(1,50,(4,6))
arr

array([[33, 11, 24, 13, 14, 40],
       [17, 35, 19, 34, 12, 33],
       [34, 11, 15, 23, 10, 45],
       [14,  9,  6, 39, 33,  5]])

In [4]:
#along the second axis
#Mean
print('Mean of the array: ',arr.mean(axis=1))
#standard deviation
print('Standard Deviation of the array: ',arr.std(axis=1))
#variance
print('Variance of the array: ',arr.var(axis=1))

('Mean of the array: ', array([ 22.5       ,  25.        ,  23.        ,  17.66666667]))
('Standard Deviation of the array: ', array([ 10.90489187,   9.25562892,  12.79322737,  13.38739042]))
('Variance of the array: ', array([ 118.91666667,   85.66666667,  163.66666667,  179.22222222]))


In [5]:
#part b
B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]
arr1 = np.array(B)
arr1

array([56, 48, 22, 41, 78, 91, 24, 46,  8, 33])

In [6]:
print("Sorted array: ",np.sort(arr1))
print("Indices of the sorted elements of a given array: ",np.argsort(arr1))

('Sorted array: ', array([ 8, 22, 24, 33, 41, 46, 48, 56, 78, 91]))
('Indices of the sorted elements of a given array: ', array([8, 2, 6, 9, 3, 7, 1, 0, 4, 5], dtype=int64))


In [7]:
#part c
m = int(input('Enter the number of rows(m): '))
n = int(input('Enter the number of columns(n): '))
arr2 = np.random.randint(1,100,(m,n))
print(arr2)
print('Shape: ',arr2.shape)
print('Type: ',type(arr2))
print('Data Type: ',arr2.dtype)
arr2 = arr2.reshape(n,m)
print('After reshaping: \n',arr2)
print('New Shape: ',arr2.shape)

Enter the number of rows(m): 5
Enter the number of columns(n): 6
[[35 44 50 41 13 92]
 [63 27 20 64 95 51]
 [43  1 99 69 60 76]
 [18 90 64 83 76 14]
 [19 72 50 42 24 21]]
('Shape: ', (5L, 6L))
('Type: ', <type 'numpy.ndarray'>)
('Data Type: ', dtype('int32'))
('After reshaping: \n', array([[35, 44, 50, 41, 13],
       [92, 63, 27, 20, 64],
       [95, 51, 43,  1, 99],
       [69, 60, 76, 18, 90],
       [64, 83, 76, 14, 19],
       [72, 50, 42, 24, 21]]))
('New Shape: ', (6L, 5L))


In [17]:
#part D
x = np.array([1, 0, 3, 4])
print("ORIGINAL ARRAY ::--> ",x)
print("\nTest if none of the elements of the said array is zero ::--> ", np.all(x))

res = np.where(x == 0)
print("The index of the  zero elements is :: ",res)


x = np.array([1, 0, 0, 3, 2, 0])
print("\n-------------------------------------------------------")
print("\nORIGINAL ARRAY ::--> ",x)
print("\nTest whether any of the elements of a given array is non-zero ::",np.any(x))
res = np.where(x != 0)
print("The index of the non- zero elements is :: ",res)
x = np.array([0, 0, 0, 0])


a = np.array([1, 0, np.nan, 3, np.nan])
print("\n-------------------------------------------------------")
print("\nORIGINAL ARRAY ::--> ",a)
print("\nTest element-wise for NaN :: ",np.isnan(a))

res = np.where(np.isnan(a) == True)
print("The index of the  zero elements is :: ",res)

('ORIGINAL ARRAY ::--> ', array([1, 0, 3, 4]))
('\nTest if none of the elements of the said array is zero ::--> ', False)
('The index of the  zero elements is :: ', (array([1], dtype=int64),))

-------------------------------------------------------
('\nORIGINAL ARRAY ::--> ', array([1, 0, 0, 3, 2, 0]))
('\nTest whether any of the elements of a given array is non-zero ::', True)
('The index of the non- zero elements is :: ', (array([0, 3, 4], dtype=int64),))

-------------------------------------------------------
('\nORIGINAL ARRAY ::--> ', array([  1.,   0.,  nan,   3.,  nan]))
('\nTest element-wise for NaN :: ', array([False, False,  True, False,  True], dtype=bool))
('The index of the  zero elements is :: ', (array([2, 4], dtype=int64),))
